apiVersion: v1
kind: Namespace
metadata:
  name: ai-services
  labels:
    name: ai-services
    purpose: global-ai-infrastructure
---
apiVersion: v1
kind: Namespace
metadata:
  name: ai-agents
  labels:
    name: ai-agents
    purpose: worker-agent-jobs
